routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Student
    Route::delete('students/destroy', 'StudentController@massDestroy')->name('students.massDestroy');
    Route::resource('students', 'StudentController', ['except' => ['show']]);

    // Mark
    Route::delete('marks/destroy', 'MarkController@massDestroy')->name('marks.massDestroy');
    Route::resource('marks', 'MarkController', ['except' => ['show']]);
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Mark.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mark extends Model
{
    use HasFactory;

    public const TERM_SELECT = [
        'One' => 'One',
        'Two' => 'Two',
    ];

    public $table = 'marks';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name_id',
        'term',
        'maths',
        'science',
        'history',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
    /**
     * Relaton to Student Table
     */
    public function name()
    {
        return $this->belongsTo(Student::class, 'name_id');
    }
    /**
     * Date mutator
     */
    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/MarkController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyMarkRequest;
use App\Http\Requests\StoreMarkRequest;
use App\Http\Requests\UpdateMarkRequest;
use App\Models\Mark;
use App\Models\Student;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class MarkController extends Controller
{
    /**
     * @author Adinath
     * view list
     */
    public function index()
    {
        $marks = Mark::with(['name'])->get();
        return view('admin.marks.index', compact('marks'));
    }

    /**
     * @author Adinath
     * Create Mark
     */
    public function create()
    {
        

        $names = Student::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.marks.create', compact('names'));
    }

    /**
     * @author Adinath
     * Save Mark details
     */
    public function store(StoreMarkRequest $request)
    {
        $mark = Mark::create($request->all());

        return redirect()->route('admin.marks.index');
    }

    /**
     * @author Adinath
     * @param Mark
     * Edit Mark
     */
    public function edit(Mark $mark)
    {
        
        $names = Student::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $mark->load('name');

        return view('admin.marks.edit', compact('names', 'mark'));
    }

    /**
     * @author Adinath
     * Update Mark
     * @param Request,Mark
     */
    public function update(UpdateMarkRequest $request, Mark $mark)
    {
        $mark->update($request->all());

        return redirect()->route('admin.marks.index');
    }

    /**
     * @author Adinath
     * Delete Mark
     * @param Mark
     */
    public function destroy(Mark $mark)
    {
        
        $mark->delete();

        return back();
    }

    /**
     * @author Adinath
     * Delete Marks
     * @return Response
     */
    public function massDestroy(MassDestroyMarkRequest $request)
    {
        Mark::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/marks/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.mark.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.marks.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name_id">{{ trans('cruds.mark.fields.name') }}</label>
                <select class="form-control select2 {{ $errors->has('name') ? 'is-invalid' : '' }}" name="name_id" id="name_id" required>
                    @foreach($names as $id => $entry)
                        <option value="{{ $id }}" {{ old('name_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.mark.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required">{{ trans('cruds.mark.fields.term') }}</label>
                <select class="form-control {{ $errors->has('term') ? 'is-invalid' : '' }}" name="term" id="term" required>
                    <option value disabled {{ old('term', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
                    @foreach(App\Models\Mark::TERM_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('term', '') === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('term'))
                    <span class="text-danger">{{ $errors->first('term') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.mark.fields.term_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="maths">{{ trans('cruds.mark.fields.maths') }}</label>
                <input class="form-control {{ $errors->has('maths') ? 'is-invalid' : '' }}" type="number" name="maths" id="maths" value="{{ old('maths', '') }}" step="1" required>
                @if($errors->has('maths'))
                    <span class="text-danger">{{ $errors->first('maths') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.mark.fields.maths_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="science">{{ trans('cruds.mark.fields.science') }}</label>
                <input class="form-control {{ $errors->has('science') ? 'is-invalid' : '' }}" type="number" name="science" id="science" value="{{ old('science', '') }}" step="1" required>
                @if($errors->has('science'))
                    <span class="text-danger">{{ $errors->first('science') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.mark.fields.science_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="history">{{ trans('cruds.mark.fields.history') }}</label>
                <input class="form-control {{ $errors->has('history') ? 'is-invalid' : '' }}" type="number" name="history" id="history" value="{{ old('history', '') }}" step="1" required>
                @if($errors->has('history'))
                    <span class="text-danger">{{ $errors->first('history') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.mark.fields.history_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/marks/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.mark.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.marks.update", [$mark->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name_id">{{ trans('cruds.mark.fields.name') }}</label>
                <select class="form-control select2 {{ $errors->has('name') ? 'is-invalid' : '' }}" name="name_id" id="name_id" required>
                    @foreach($names as $id => $entry)
                        <option value="{{ $id }}" {{ (old('name_id') ? old('name_id') : $mark->name->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.mark.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required">{{ trans('cruds.mark.fields.term') }}</label>
                <select class="form-control {{ $errors->has('term') ? 'is-invalid' : '' }}" name="term" id="term" required>
                    <option value disabled {{ old('term', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
                    @foreach(App\Models\Mark::TERM_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('term', $mark->term) === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('term'))
                    <span class="text-danger">{{ $errors->first('term') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.mark.fields.term_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="maths">{{ trans('cruds.mark.fields.maths') }}</label>
                <input class="form-control {{ $errors->has('maths') ? 'is-invalid' : '' }}" type="number" name="maths" id="maths" value="{{ old('maths', $mark->maths) }}" step="1" required>
                @if($errors->has('maths'))
                    <span class="text-danger">{{ $errors->first('maths') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.mark.fields.maths_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="science">{{ trans('cruds.mark.fields.science') }}</label>
                <input class="form-control {{ $errors->has('science') ? 'is-invalid' : '' }}" type="number" name="science" id="science" value="{{ old('science', $mark->science) }}" step="1" required>
                @if($errors->has('science'))
                    <span class="text-danger">{{ $errors->first('science') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.mark.fields.science_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="history">{{ trans('cruds.mark.fields.history') }}</label>
                <input class="form-control {{ $errors->has('history') ? 'is-invalid' : '' }}" type="number" name="history" id="history" value="{{ old('history', $mark->history) }}" step="1" required>
                @if($errors->has('history'))
                    <span class="text-danger">{{ $errors->first('history') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.mark.fields.history_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/marks/index.blade.php
@extends('layouts.admin')
@section('content')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.marks.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.mark.title_singular') }}
            </a>
        </div>
    </div>
<div class="card">
    <div class="card-header">
        {{ trans('cruds.mark.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Mark">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.mark.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.mark.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.mark.fields.term') }}
                        </th>
                        <th>
                            {{ trans('cruds.mark.fields.maths') }}
                        </th>
                        <th>
                            {{ trans('cruds.mark.fields.science') }}
                        </th>
                        <th>
                            {{ trans('cruds.mark.fields.history') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($marks as $key => $mark)
                        <tr data-entry-id="{{ $mark->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $mark->id ?? '' }}
                            </td>
                            <td>
                                {{ $mark->name->name ?? '' }}
                            </td>
                            <td>
                                {{ App\Models\Mark::TERM_SELECT[$mark->term] ?? '' }}
                            </td>
                            <td>
                                {{ $mark->maths ?? '' }}
                            </td>
                            <td>
                                {{ $mark->science ?? '' }}
                            </td>
                            <td>
                                {{ $mark->history ?? '' }}
                            </td>
                            <td>

                                    <a class="btn btn-xs btn-info" href="{{ route('admin.marks.edit', $mark->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                    <form action="{{ route('admin.marks.destroy', $mark->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Mark:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection